# Created on Jan 24, 2019
#
# @author: Jim Yin


# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

import time


def prob_002():
    a = 1
    b = 2
    result = 2
    while a <= 4000000:
        b, a = b + a, b
        if b % 2 == 0:
            result += b

    print(result)


if __name__ == '__main__':
    start_time = time.perf_counter()
    prob_002()
    end_time = time.perf_counter()
    print(f'Time taken = {end_time - start_time} sec')


# 4613732
# Time taken = 3.449999999999287e-05 sec

