# Created on May 26, 2022
#
# @author: Jim Yin


# How many distinct terms are in the sequence generated by a**b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

import time


def main():
    print(len(set((a**b for a in range(2, 101) for b in range(2, 101)))))


if __name__ == '__main__':
    start_time = time.perf_counter()
    main()
    end_time = time.perf_counter()
    print(f'Time taken = {end_time - start_time} sec')


# 9183
# Time taken = 0.007308200000000001 sec
